name: 2. Variables
run-name : ${{github.actor}} is testing out Github Actions

on:
  workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - name: Printing the Repository Variables
          run: echo "The Value of WELCOME is ${{ vars.WELCOME }}"
        
        - name: Setting and Printing the environment variables
          run: echo "The Firdt name is ${{ env.FIRSTNAME }} and last name is ${{ env.LASTNAME }} "
          env: 
            FIRSTNAME: "Sourabh"
            LASTNAME: "Kaujalgi"
            

