name : 3. Testing Variables Based on th Environment

run-name : ${{github.actor}} is running the ${{github.workflow}}

on:
    - workflow_dispatch

jobs:
    dev_deployment: 
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Print Dev Environment Variables
              run: echo "The value of Dev environment variable is ${{ vars.HOSTNAME }}"

    qa_deployment: 
        runs-on: ubuntu-latest
        environment: qa
        steps:
            - name: Print QA Environment Variables
              run: echo "The value of QA environment variable is ${{ vars.HOSTNAME }}"
    
    prod_deployment: 
         runs-on: ubuntu-latest
         environment: prod
         steps:
            - name: Print PROD Environment Variables
              run: echo "The value of PROD environment variable is ${{ vars.HOSTNAME }}"
        
