name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment you want to deploy"
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development

      version:
        description: "What version are you deploying? (e.g. v1.0.0)"
        type: string
        required: false
        default: "v1.0.0"

      run_tests:
        description: "Should run before deploying?"
        type: boolean
        default: true

jobs:
  learn-variables:
    runs-on: ubuntu-latest

    env:
      APP_NAME: "my-coding-adda-app"
      NODE_VERSION: "20"

    steps:
      - name: "Step 1 - Show user inputs"
        run: |
          echo "============="
          echo "Inputs you provided:"
          echo "============="
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          echo "Run Tests: ${{ inputs.run_tests }}"

      - name: "Step 2 - Use environment variables"
        run: |
          echo "============="
          echo "Environment Variables:"
          echo "============="
          echo "App Name: $APP_NAME"
          echo "Node Version: $NODE_VERSION"

      - name: "Step 3 - Use a secret"
        env:
          MY_KEY: ${{ secrets.MY_API_KEY }}

        run: |
          echo "==============================="
          echo "Secrets"
          echo "==============================="
          echo "API Key is set"
          echo "First 4 chars: ${MY_KEY:0:4}***"
          