name: Workflow Commands

on:
  push:

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"

      - name: Setting a debug message with params
        run: echo "::debug file=app.js,line=2,endLine=3,col=5,endColumn=7,title=Debug title::Missing Semicolon"

      - name: Setting a warning message with params
        run: echo "::warning file=app.js,line=2,endLine=3,col=5,endColumn=7,title=Warning title::Missing Semicolon"

      - name: Setting a notice message with params
        run: echo "::notice file=app.js,line=2,endLine=3,col=5,endColumn=7,title=Notice title::Missing Semicolon"

      - name: Group of Logs
        run: |
         echo "::group::My group title"
         echo "Inside group"
         echo "::endgroup::"
      - name: Masking  a value
        run: echo "::add-mask::Secrete String"
      - name: Echo a secrete
        run: echo "Secrete String"      